AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Solução AWS que usa Lambda, EventBridge, SNS e CloudFormation para monitorar
  a criação de buckets S3 e enviar notificações via SNS com o usuário que criou o bucket.

Parameters:
  AccountID:
    Type: String
    Description: ID AWS Account
  Region:
    Type: String
    Description: Region AWS Account
  Email:
    Type: String
    Description: Mail or mail group for notifications

Resources:
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "s3.amazonaws.com"
          eventName:
            - "CreateBucket"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "TargetFunction"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "index.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          sns_client = boto3.client('sns')

          def handler(event, context):
              detail = event['detail']
              user_identity = detail['userIdentity']
              user = user_identity.get('userName', user_identity.get('principalId'))
              bucket_name = detail['requestParameters']['bucketName']
              message = f"Usuário {user} criou um bucket S3 com nome {bucket_name}."
              sns_client.publish(
                  TopicArn=f'arn:aws:sns:{os.environ["Region"]}:{os.environ["ID"]}:S3Notifications',
                  Message=message,
                  Subject='Novo bucket S3 criado'
              )
              return {
                  'statusCode': 200,
                  'body': json.dumps('Mensagem enviada com sucesso!')
              }
      Runtime: "python3.9"
      Timeout: 30
      Environment:
        Variables:
          ID: !Ref AccountID
          Region: !Ref Region

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: !Sub "arn:aws:sns:${Region}:${AccountID}:S3Notifications"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeRule.Arn

  S3NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "S3Notifications"
      Subscription:
        - Endpoint: "lucas.cardoso@darede.com.br"
          Protocol: "email"

Outputs:
  SNSTopicArn:
    Description: "ARN do tópico SNS para notificações de S3."
    Value: !Ref S3NotificationTopic
